// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchInstall(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BatchInstall'](arg1, arg2, arg3, arg4, arg5);
}

export function BatchScreenshot(arg1, arg2) {
  return window['go']['main']['App']['BatchScreenshot'](arg1, arg2);
}

export function BatchStartScrcpy(arg1) {
  return window['go']['main']['App']['BatchStartScrcpy'](arg1);
}

export function BatchStopScrcpy(arg1) {
  return window['go']['main']['App']['BatchStopScrcpy'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ClearFinishedTasks() {
  return window['go']['main']['App']['ClearFinishedTasks']();
}

export function ClearPackage(arg1, arg2) {
  return window['go']['main']['App']['ClearPackage'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRemote'](arg1, arg2, arg3);
}

export function DeviceInfo(arg1) {
  return window['go']['main']['App']['DeviceInfo'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ForegroundActivity(arg1) {
  return window['go']['main']['App']['ForegroundActivity'](arg1);
}

export function Forward(arg1, arg2, arg3) {
  return window['go']['main']['App']['Forward'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetToolPaths() {
  return window['go']['main']['App']['GetToolPaths']();
}

export function InstallApk(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InstallApk'](arg1, arg2, arg3, arg4, arg5);
}

export function IsLogcatRunning() {
  return window['go']['main']['App']['IsLogcatRunning']();
}

export function IsScrcpyRunning(arg1) {
  return window['go']['main']['App']['IsScrcpyRunning'](arg1);
}

export function IsScreenRecording(arg1) {
  return window['go']['main']['App']['IsScreenRecording'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListPackages(arg1, arg2) {
  return window['go']['main']['App']['ListPackages'](arg1, arg2);
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteDir'](arg1, arg2);
}

export function ListRemoteEntries(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteEntries'](arg1, arg2);
}

export function ListScrcpy() {
  return window['go']['main']['App']['ListScrcpy']();
}

export function ListScreenRecords() {
  return window['go']['main']['App']['ListScreenRecords']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function MkdirRemote(arg1, arg2) {
  return window['go']['main']['App']['MkdirRemote'](arg1, arg2);
}

export function Pair(arg1, arg2) {
  return window['go']['main']['App']['Pair'](arg1, arg2);
}

export function PortList(arg1) {
  return window['go']['main']['App']['PortList'](arg1);
}

export function PortRemoveAll(arg1) {
  return window['go']['main']['App']['PortRemoveAll'](arg1);
}

export function PullFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullFile'](arg1, arg2, arg3);
}

export function PushFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushFile'](arg1, arg2, arg3);
}

export function Reboot(arg1, arg2) {
  return window['go']['main']['App']['Reboot'](arg1, arg2);
}

export function RenameRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRemote'](arg1, arg2, arg3);
}

export function Reverse(arg1, arg2, arg3) {
  return window['go']['main']['App']['Reverse'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Screenshot(arg1, arg2) {
  return window['go']['main']['App']['Screenshot'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SelectSaveFile(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2);
}

export function Shell(arg1, arg2) {
  return window['go']['main']['App']['Shell'](arg1, arg2);
}

export function StartLogcat(arg1, arg2) {
  return window['go']['main']['App']['StartLogcat'](arg1, arg2);
}

export function StartScrcpy(arg1) {
  return window['go']['main']['App']['StartScrcpy'](arg1);
}

export function StartScreenRecord(arg1, arg2) {
  return window['go']['main']['App']['StartScreenRecord'](arg1, arg2);
}

export function StopLogcat() {
  return window['go']['main']['App']['StopLogcat']();
}

export function StopScrcpy(arg1) {
  return window['go']['main']['App']['StopScrcpy'](arg1);
}

export function StopScreenRecord(arg1) {
  return window['go']['main']['App']['StopScreenRecord'](arg1);
}

export function Tcpip(arg1, arg2) {
  return window['go']['main']['App']['Tcpip'](arg1, arg2);
}

export function TestAdb() {
  return window['go']['main']['App']['TestAdb']();
}

export function UninstallPackage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UninstallPackage'](arg1, arg2, arg3, arg4);
}
