// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {adb} from '../models';
import {settings} from '../models';
import {scrcpy} from '../models';
import {tasks} from '../models';

export function BatchInstall(arg1:Array<string>,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<Array<string>>;

export function BatchScreenshot(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function BatchStartScrcpy(arg1:Array<string>):Promise<Array<string>>;

export function BatchStopScrcpy(arg1:Array<string>):Promise<Array<string>>;

export function Bootstrap():Promise<main.BootstrapData>;

export function CancelTask(arg1:string):Promise<void>;

export function ClearFinishedTasks():Promise<void>;

export function ClearPackage(arg1:string,arg2:string):Promise<string>;

export function Connect(arg1:string):Promise<string>;

export function DeleteRemote(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeviceInfo(arg1:string):Promise<adb.DeviceInfo>;

export function DiagnosePackage(arg1:string,arg2:string):Promise<string>;

export function DisablePackage(arg1:string,arg2:string):Promise<string>;

export function Disconnect(arg1:string):Promise<string>;

export function EnablePackage(arg1:string,arg2:string):Promise<string>;

export function ForceStopPackage(arg1:string,arg2:string):Promise<string>;

export function ForegroundActivity(arg1:string):Promise<string>;

export function Forward(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function GetToolPaths():Promise<Record<string, string>>;

export function InstallApk(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<string>;

export function IsLogcatRunning():Promise<boolean>;

export function IsPackageDebuggable(arg1:string,arg2:string):Promise<boolean>;

export function IsScrcpyRunning(arg1:string):Promise<boolean>;

export function IsScreenRecording(arg1:string):Promise<boolean>;

export function LaunchPackage(arg1:string,arg2:string):Promise<string>;

export function ListDevices():Promise<Array<adb.Device>>;

export function ListPackages(arg1:string,arg2:string):Promise<Array<adb.PackageInfo>>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<string>;

export function ListRemoteEntries(arg1:string,arg2:string):Promise<Array<adb.RemoteEntry>>;

export function ListRunningServices(arg1:string):Promise<Array<adb.RunningService>>;

export function ListScrcpy():Promise<Array<scrcpy.Session>>;

export function ListScreenRecords():Promise<Array<adb.RecordSession>>;

export function ListTasks():Promise<Array<tasks.Item>>;

export function MkdirRemote(arg1:string,arg2:string):Promise<void>;

export function Pair(arg1:string,arg2:string):Promise<string>;

export function PortList(arg1:string):Promise<Record<string, string>>;

export function PortRemoveAll(arg1:string):Promise<void>;

export function PullFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PushFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Reboot(arg1:string,arg2:string):Promise<void>;

export function RenameRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Reverse(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function Screenshot(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:Array<string>):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function Shell(arg1:string,arg2:string):Promise<string>;

export function StartLogcat(arg1:string,arg2:boolean):Promise<void>;

export function StartScrcpy(arg1:string):Promise<void>;

export function StartScreenRecord(arg1:string,arg2:string):Promise<void>;

export function StopLogcat():Promise<void>;

export function StopScrcpy(arg1:string):Promise<void>;

export function StopScreenRecord(arg1:string):Promise<string>;

export function StopService(arg1:string,arg2:string):Promise<string>;

export function Tcpip(arg1:string,arg2:number):Promise<string>;

export function TestAdb():Promise<string>;

export function UninstallPackage(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<string>;
